// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1_YqzUbC6vGvu8pINqeKLnPOag7uyHx4',
    appId: '1:216241102108:web:90f196c3748d04f53d6ed9',
    messagingSenderId: '216241102108',
    projectId: 'puctime-84a21',
    authDomain: 'puctime-84a21.firebaseapp.com',
    databaseURL: 'https://puctime-84a21-default-rtdb.firebaseio.com',
    storageBucket: 'puctime-84a21.appspot.com',
    measurementId: 'G-NBW9KPKYSJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeXLN_PExqOM8f3hAnrJvTgjbAroBbFw',
    appId: '1:216241102108:android:15006c52981168023d6ed9',
    messagingSenderId: '216241102108',
    projectId: 'puctime-84a21',
    databaseURL: 'https://puctime-84a21-default-rtdb.firebaseio.com',
    storageBucket: 'puctime-84a21.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB5rqGzyvVcJuifzpgLVAErdPzkwmYlbC8',
    appId: '1:216241102108:ios:5140a67ec2169da83d6ed9',
    messagingSenderId: '216241102108',
    projectId: 'puctime-84a21',
    databaseURL: 'https://puctime-84a21-default-rtdb.firebaseio.com',
    storageBucket: 'puctime-84a21.appspot.com',
    iosBundleId: 'com.example.firebaseImplement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB5rqGzyvVcJuifzpgLVAErdPzkwmYlbC8',
    appId: '1:216241102108:ios:5140a67ec2169da83d6ed9',
    messagingSenderId: '216241102108',
    projectId: 'puctime-84a21',
    databaseURL: 'https://puctime-84a21-default-rtdb.firebaseio.com',
    storageBucket: 'puctime-84a21.appspot.com',
    iosBundleId: 'com.example.firebaseImplement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1_YqzUbC6vGvu8pINqeKLnPOag7uyHx4',
    appId: '1:216241102108:web:11836975b7300af23d6ed9',
    messagingSenderId: '216241102108',
    projectId: 'puctime-84a21',
    authDomain: 'puctime-84a21.firebaseapp.com',
    databaseURL: 'https://puctime-84a21-default-rtdb.firebaseio.com',
    storageBucket: 'puctime-84a21.appspot.com',
    measurementId: 'G-H16BQM3DSF',
  );

}